### ISSUE TITLE
NaN semantics

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#11]
In Java code, floating point semantics has NaN == NaN false. Consequently we cannot interpret the same == as logical equality. So what should be done with FP (floating point) operators and values in JML? Note that Java users are often confused about FP operators also, or at least forget to take into account the IEEE features of NaN, infinities and positive/negative zero.

a) Allow the Java == in JML expressions, but transform FP values and operators to some logical values and operators underneath (users get conventional FP semantics, but might get confused about the logic).

//@ ensures \result == a; // Cannot be proven (a might be NaN)
double m(double a) {
   return a;
}

b) Consider FP operators in JML undefined unless it can be proven that the isNaN() is false on the operands. This would retain a logical subset of FP semantics.

//@ ensures !Double.isNaN(a) ==> \result == a;
double m(double a) {
   return a;
}

Pro: Semantics are clear. Con: isNaN guards everywhere.

c) == in JML is always a logical equality ad not the same as == in Java for FP values.

//@ ensures \result == a;
double m(double a) {
   boolean b = a == a;
   //@ assert b; // Not necessarily true.
   //@ assert a == a; // OK, even for NaN values
   return a;
}

Pro: Don't need as many isNaN guards,; Con:  users might be confused about == and might forget about the possibility of NaN values

I prefer (b) or (c) to (a), but there may well be alternatives that I have not yet thought of. (c) is clean; (b) is more explicit at the expense of being wordier

**Comment by leavens** [comment]
Hi David and all,

I think there is a third alternative for Java code:

c) use the Java floating-point semantics (i.e., treat all floating-point comparisons as returning false if any argument is NaN and all float-valued operations as returning NaN when any argument is NaN).

Thus to say anything reasonable, one has to prevent NaN from arising as a possible value.  Effectively this has the same advantages and disadvantages as (b), one must guard all specifications against NaN as a possible value, but once that is done, one can use something like a more mathematical semantics.

I think it's best if tools give warnings for any use of a comparison operator when one argument could be NaN. (Indeed I would argue that == and != should almost never be used with floating point numbers and thus it might be reasonable to warn against all uses of these operators for floating-point numbers.)

        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

From: David Cok ***@***.***>
Sent: Wednesday, December 1, 2021 10:27 AM
To: JavaModelingLanguage/RefMan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JavaModelingLanguage/RefMan] NaN semantics (Issue #11)


In Java code, floating point semantics has NaN == NaN false. Consequently we cannot interpret the same == as logical equality. So what should be done with FP (floating point) operators and values in JML? Note that Java users are often confused about FP operators also, or at least forget to take into account the IEEE features of NaN, infinities and positive/negative zero.

a) Allow the Java == in JML expressions, but transform FP values and operators to some logical values and operators underneath (users get conventional FP semantics, but might get confused about the logic).

//@ ensures \result == a; // Cannot be proven (a might be NaN)
double m(double a) {
return a;
}

b) Consider FP operators in JML undefined unless it can be proven that the isNaN() is false on the operands. This would retain a logical subset of FP semantics.

//@ ensures !Double.isNaN(a) ==> \result == a;
double m(double a) {
return a;
}

Pro: Semantics are clear. Con: isNaN guards everywhere.

I prefer (b) to (a), but there may well be alternatives that I have not yet thought of.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJavaModelingLanguage%2FRefMan%2Fissues%2F11&data=04%7C01%7CLeavens%40ucf.edu%7C3e9582b6bdc84a98506b08d9b4df12c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637739692453756067%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0M6VMLP8EHpYy2aPzdtQ3plGTcxrkoxkM1ADLXnCUlg%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC53NPOELW4HBJBXKMRFLYTUOY5FVANCNFSM5JEYNQYA&data=04%7C01%7CLeavens%40ucf.edu%7C3e9582b6bdc84a98506b08d9b4df12c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637739692453766061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WvcqXe4%2BRDVdbCe%2F4Xyvebh8Ru99ptmOiis9c3q9%2Feg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CLeavens%40ucf.edu%7C3e9582b6bdc84a98506b08d9b4df12c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637739692453776054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zycn841xwwyYJ%2Fp4i1iml%2FDV0BDUo8584nSDxTcb4D4%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CLeavens%40ucf.edu%7C3e9582b6bdc84a98506b08d9b4df12c3%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637739692453786050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BRAthR0UkgUEwBDu6D5nPVc793JwKhle%2BaWEE216cMU%3D&reserved=0>.

**Comment by davidcok** [comment]
I think what you are describing is (b). If we leave out (guard against NaN), then == for Java FP and == in logic are the same. Whoops - that is not true for signed zero. There we have 0.0 == -0.0 is true. SO my previous alternatives need revising.

Note that
new Double(0.0).equals(new Double(-0.0)) is false
But
0.0 == -0.0 is true
And
   Double.NaN == Double.NaN is false
But
 Double.valueOf(Double.NaN).equals(Double.valueOf(Double.NaN)) is true

So actually .equals appears closer to logical equality than ==.

**Comment by leavens** [comment]
Hi David and all,

I agree with you that .equals for floats is closer to what we think of as equality in logic than == is.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by mattulbrich** [comment]
I am a pretty strong advocate that every Java expression have the same 
semantics when occurring in JML. (I am aware that a+b can be interpreted 
on \bigint when in JML.)

Hence, in my opinion, `0.0d == -0.0d` is true and `Double.NaN == 
Double.NaN` better be false.

In KeY we have made an effort to map the Java semantics to the logic. 
The Java equality `==` does not become a logical =, but `fpEq` which is 
not reflexive for NaN. Seems to work out ok with the SMT solvers.

**Comment by leavens** [comment]
Hi Mattias and all,

Within a given arithmetic mode we need a well-defined semantics. In Java mode the semantics should match Java's semantics as closely as possible.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
If == in JML is to mean precisely what it means in Java (at least on Java values), then do we need an alternate function or operator to mean logical equality, such as === or \leq
It would have different semantics perhaps only for FP values.

**Comment by leavens** [comment]
Hi David and all,

It may indeed be sensible to have a new operator for equality that is the right thing for floating point numbers (and other types). However, I wonder if we could use a pure model method instead of doing that, and recognize that calls to that method are to be translated into equality tests in SMT?


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
OK. The choices would be
a) a new operator, e.g. ===
b) a new builtin, e.g. \eq(x,y)
c) a model method, e.g. Double.eq(x,y)

The last of these can be done with no change to JML other than the presciption of its meaning and that it is defined.

I take it you are voting for (c). Do you have a name to propose?

**Comment by leavens** [comment]
Hi David and all,

For a model method for floating point equality, I think realEquals might be good, if equals itself is not suitable.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
equals would likely be confusing. I’d prefer something shorter than realEquals

**Comment by leavens** [comment]
Hi David and all,

In the design of JML I have tried to avoid acronyms and use actual words so that specifications are easier to read and learn. I think "realEquals" is nice because it refers to the mathematical real numbers in its name.  But I'm open to suggestions...


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by davidcok** [comment]
What about ‘identical’?
(It is not quite identical when compared by bit vector because of multiple representations of NaN, but it is close enough for me)

- David

**Comment by leavens** [comment]
Hi David,

That would be fine, but perhaps "same" or "similar" would be good alternatives...

        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by mattulbrich** [comment]
A little late, but my thought would also be to have a static method "same" encoding this. It could actually be implemented in Java, I think, like

````java
//@ public normal_behaviour
//@       ensures \result <==> (f1 == f2 && sign(f1) == sign(f2)) || (Float.isNan(f1) && Float.isNaN(f2));
//+KeY@   assignable \strictly_nothing;

public /*@ pure */ boolean same(float f1, float f2) {
   return Float.floatToIntBits(f1) == Float.floatToIntBits(f2);
}
````

Coincidently this is the same as `Float.valueOf(f1).equals(Float.valueOf(f2))`.

(Unfortunately, the `sign` method does not exist. ...)

**Comment by davidcok** [comment]
I'm OK with the name ’same’. And a Java implementation is good for RAC.
As to the specs, one has to watch out for recursion. I’d probably use ’same’ as the base primitive, because it maps best into logical equality. However, I have not looked at how the SMT theory handles FP-equality.

- David

**Comment by leavens** [comment]
Hi Mattias, David, and all,

Yes, "same" is a reasonable name for this, I agree.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

**Comment by leavens** [comment]
So, it seems that we agree to use model methods Double.same and Float.same for the equality operator on Doubles and Floats.  I agree that Mattias's specification and code makes sense.

//@ public normal_behaviour
//@       ensures \result <==> (f1 == f2 && sign(f1) == sign(f2)) || (Float.isNan(f1) && Float.isNaN(f2));
//+KeY@   assignable \strictly_nothing;

public /*@ pure */ boolean same(float f1, float f2) {
   return Float.floatToIntBits(f1) == Float.floatToIntBits(f2);
}

**Comment by davidcok** [comment]
And that == in JML expressions means the same as it does in Java.
I think this is resolved. Closing.
