### ISSUE TITLE
Deprecate `nowarn`?

### ISSUE THREAD

**Issue by davidcok** [JavaModelingLanguage/RefMan#21]
I'd like to deprecate `nowarn`.
I've never used it. Its semantics is not entirely clear but it seems unsound in the way assume is.
It is an unusual construction from a parsing perspective because it is a line-oriented annotation that can appear anywhere.
So I think it is a (small) language simplification.

**Comment by leavens** [comment]
Hi David and all,

That seems fine to me. This feature was originally in ESC/Java.


        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

From: David Cok ***@***.***>
Sent: Monday, December 13, 2021 8:59 AM
To: JavaModelingLanguage/RefMan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JavaModelingLanguage/RefMan] Deprecate `nowarn`? (Issue #21)


I'd like to deprecate nowarn.
I've never used it. Its semantics is not entirely clear but it seems unsound in the way assume is.
It is an unusual construction from a parsing perspective because it is a line-oriented annotation that can appear anywhere.
So I think it is a (small) language simplification.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJavaModelingLanguage%2FRefMan%2Fissues%2F21&data=04%7C01%7CLeavens%40ucf.edu%7Cb340773efb60430b236a08d9be40ba72%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637750007491954680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S8cSrshimtyfxBAKtDkIOsjlYvnAXVJ8tfyKVVTMXCU%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC53NPO64ANRZFNMBQFTCXDUQX32TANCNFSM5J6GT6JA&data=04%7C01%7CLeavens%40ucf.edu%7Cb340773efb60430b236a08d9be40ba72%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637750007491964677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cX%2B9i4CqPYcT6vayM0o1qiKacAtvboDMYIruZu%2BC6KY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CLeavens%40ucf.edu%7Cb340773efb60430b236a08d9be40ba72%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637750007491974671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vwIrv7UhVhw08p1BhsJCVKHXrutaPM7UO6Ec%2BsqP3hk%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CLeavens%40ucf.edu%7Cb340773efb60430b236a08d9be40ba72%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637750007491984669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=13OJPUfJBA8tfMfFfG0imEYu5nJBNvFQAFx8VoVhGYs%3D&reserved=0>.

**Comment by mattulbrich** [comment]
Never used it, too.

Happy to deprecate it to make language smaller.

**Comment by wadoon** [comment]
+1

**Comment by davidcok** [comment]
Closing this issue as agreed and settled.
